### ISSUE TITLE
empty collections: return 404 or empty table

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-api#11]
Should we send a 404 when there's an empty collection or display the json with no data? `/api/reports/576/versions/20090226/next`

**Comment by jean-gui** [comment]
I fixed a bug for non-existing spec versions (yet to be deployed). For the rest, I believe the current behaviour is correct:
- /users/foobar references a non existing user, so that's a 404
- /specifications/xxx/versions/yyy/successor returns an empty collection because the spec version exists but has no successors
