### ISSUE TITLE
Data about specification editors appears to be incomplete

### ISSUE THREAD

**Issue by ndw** [w3c/w3c-api#65]
Mike Smith suggested I report this. It appears that the data about specification editors behind the specifications API is incomplete. Consider:

`GET "https://api.w3.org/specifications/REC-rdf-syntax/versions"` returns, in part,

```
       "version-history": [
            {
                "href": "https:\/\/api.w3.org\/specifications\/WD-rdf-syntax\/versions\/19980819",
                "title": "RDF\/XML Syntax Specification (Revised)"
            },
```

but `GET https://api.w3.org/specifications/REC-rdf-syntax/versions/19980819/editors"` returns:

```
{
    "page": 1,
    "limit": 100,
    "pages": 0,
    "total": 0,
    "_links": {
        "up": {
            "href": "https:\/\/api.w3.org\/specifications\/WD-rdf-syntax\/versions\/19980819"
        },
        "self": {
            "href": "https:\/\/api.w3.org\/specifications\/WD-rdf-syntax\/versions\/19980819\/editors?page=1&items=100"
        },
        "first": {
            "href": "https:\/\/api.w3.org\/specifications\/WD-rdf-syntax\/versions\/19980819\/editors?page=1&items=100"
        },
        "last": {
            "href": "https:\/\/api.w3.org\/specifications\/WD-rdf-syntax\/versions\/19980819\/editors?page=0&items=100"
        }
    }
}                                  
```

**Comment by deniak** [comment]
@ndw: the API is indeed lacking some data for old specs because, before 2002, we were not storing these information in the RDF files.
Here's how it works. [tr.rdf](http://www.w3.org/2002/01/tr-automation/tr.rdf) only lists the latest versions of each specification so you can't get the full history of a spec from there. Instead, we have snapshots of the TR history spread into different RDF files:
- https://www.w3.org/2002/01/tr-automation/tr-pub-19951117-20020326.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20020327-20030519.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20030520-20040114.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20040114-20040601.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20040602-20050103.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20050104-20050729.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20050730-20060303.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20060304-20060822.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20060823-20070518.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20070519-20071231.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20080101-20090327.rdf
- https://www.w3.org/2002/01/tr-automation/tr-pub-20090328-20110921.rdf
- https://www.w3.org/2002/01/tr-automation/new-tr.rdf

If you combine all these files altogether, you should get the full history of /TR.
However, as you will see, the oldest RDF files are a bit incomplete.

A few years ago, we migrated all these data to a database but we still don't have the missing bits. This explains why we are missing the editors for old specs in the API.
I have a long overdue task to go through each document and fill in all the blanks but unfortunately, I'll have a hard time to take care of this in the near future.

In the meantime, I could try to identify all the specs you are mentioned as an editor and send you the list if it helps.

**Comment by ndw** [comment]
Oh, goodness! No, don't do anything like that. I got the data I needed in the end. I was just reporting it because Mike suggested I should. I'm good. Thanks for your help!
