### ISSUE TITLE
Expose also temporary/proposed/unofficial data using a special flag (?)

### ISSUE THREAD

**Issue by tripu** [w3c/w3c-api#66]
From a suggestion by DanielD:

There are cases when clients of the API (eg, `node-w3capi`, `Unitas`) are interested in eg groups that aren't official yet. For example, a proposed IG. Obviously, when things aren't official yet it's for a reason. But it might be useful to enable a flag `proposed` or similar, that would return also those items (assuming they exist in our DB) even if they aren't approved/launched (yet)&hellip;

I think as long as the client enables the flag explicitly, knows what it's doing and shows the data accordingly to the user, there should be no risk of misleading people with unofficial information.

**Comment by tripu** [comment]
fwiw, I don't need this feature any more. Feel free to close it, or to downgrade it in priority and leave it open as part of a backlog.

**Comment by jean-gui** [comment]
We have the notion of staging groups for IGs and WGs but this only exists internally and means "do not make the group public yet", so we cannot expose that in the API.
We could have an endpoint for proposed CGs since that's already how they work, but for other types of groups it would mean implementing a new logic to our core codebase and social changes in the way groups at large are run.

**Comment by tripu** [comment]
Thanks, @jean-gui. It sounds like too much work for a feature I don't need. I suggest closing it.
